### ISSUE TITLE
 Failed to deserialize a binary response: unknown variant `The query was not executed due to a cancelled transaction`

### ISSUE THREAD

**Issue by jaymes15** [Odonno/surrealdb-migrations-action#6]
**Describe the bug**
I am getting this error when I try to apply make migrations to a remote surrealdb 

```
Error: Failed to deserialize a binary response: unknown variant `The query was not executed due to a cancelled transaction`, expected one of `None`, `Null`, `False`, `True`, `Number`, `Strand`, `Duration`, `Datetime`, `Uuid`, `Array`, `Object`, `Geometry`, `Bytes`, `Param`, `Idiom`, `Table`, `Thing`, `Model`, `Regex`, `Block`, `Range`, `Edges`, `Future`, `Constant`, `Function`, `Subquery`, `Expression`
```

**To Reproduce**
Here is my github actions workflow file which produced this error:
```
jobs:
 
  apply_migration_staging_env:
    name: Apply Db migration to staging environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
      - name: Apply migrations
        uses: Odonno/surrealdb-migrations-action@v0.2.0
        with:
          version: 0.9.10
          address: "https://bitter-brook-3713.fly.dev/"
          ns: "test"
          db: "test"
          username: "root"
          password: "root734"
```

**Expected behavior**
I expect that migration should be applied to my remote surrealdb.
Everything works fine when I run this setup with a local instance of surreal db.
I was able to connect to my surreal db instance on fly.io via `https://surrealist.app/`

<img width="1511" alt="Screenshot 2023-07-17 at 20 25 56" src="https://github.com/Odonno/surrealdb-migrations-action/assets/46538679/09082cde-0b2d-40d9-8c52-816edcc0262a">

**Screenshot (Error)**:
<img width="1154" alt="Screenshot 2023-07-17 at 20 19 40" src="https://github.com/Odonno/surrealdb-migrations-action/assets/46538679/7a655d00-5b46-428a-bb3c-7b020ae46c4a">

**Docker-compose file**:
```

version: "3.8"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8000:8000'
    command: start --log trace --user root --pass root file:mydatabase.db
    restart: always
    volumes:
      - ./data:/data

```
